### PR TITLE
t8n: Fix deposit log and sys contract validations

### LINKED ISSUE #1337: Remaining fails filling EEST with evmone
Just adding these here for visibility! Let me know if you can reproduce or if there is anything we can do on EEST/EELS side.

EEST command:
```
uv run fill --from Osaka --until BPO4  --clean --evm-bin=../clients/evmone/build/bin/evmone-t8n -n 8
```

Filling with this PR: https://github.com/ethereum/execution-spec-tests/pull/2264

Current status:
- [x] EIP-7825 passing,
- [x] EIP-6110 passing,
- [x] EIP-7002 passing, 
- [x] EIP-7251 passing.

We can all fill tests with evmone in EEST apart from the following:
```
FAILED tests/osaka/eip7825_transaction_gas_limit_cap/test_tx_gas_limit.py::test_transaction_gas_limit_cap[fork_Osaka-tx_gas_limit_cap_exceeds_maximum1-blockchain_test_engine_from_state_test] - ethereum_test_specs.helpers.UndefinedExecutionExceptionError: Exception mismatch on Transaction ({'index': 0, 'nonce': 0}):
FAILED tests/osaka/eip7825_transaction_gas_limit_cap/test_tx_gas_limit.py::test_transaction_gas_limit_cap[fork_Osaka-tx_gas_limit_cap_exceeds_maximum2-state_test] - ethereum_test_specs.helpers.UndefinedExecutionExceptionError: Exception mismatch on Transaction ({'index': 0, 'nonce': 0}):
FAILED tests/osaka/eip7825_transaction_gas_limit_cap/test_tx_gas_limit.py::test_transaction_gas_limit_cap[fork_Osaka-tx_gas_limit_cap_exceeds_maximum2-blockchain_test_from_state_test] - ethereum_test_specs.helpers.UndefinedExecutionExceptionError: Exception mismatch on Transaction ({'index': 0, 'nonce': 0}):
FAILED tests/osaka/eip7825_transaction_gas_limit_cap/test_tx_gas_limit.py::test_transaction_gas_limit_cap[fork_Osaka-tx_gas_limit_cap_exceeds_maximum2-blockchain_test_engine_from_state_test] - ethereum_test_specs.helpers.UndefinedExecutionExceptionError: Exception mismatch on Transaction ({'index': 0, 'nonce': 0}):
FAILED tests/osaka/eip7825_transaction_gas_limit_cap/test_tx_gas_limit.py::test_transaction_gas_limit_cap[fork_Osaka-tx_gas_limit_cap_exceeds_maximum3-state_test] - ethereum_test_specs.helpers.UndefinedExecutionExceptionError: Exception mismatch on Transaction ({'index': 0, 'nonce': 0}):
FAILED tests/osaka/eip7825_transaction_gas_limit_cap/test_tx_gas_limit.py::test_transaction_gas_limit_cap[fork_Osaka-tx_gas_limit_cap_exceeds_maximum3-blockchain_test_from_state_test] - ethereum_test_specs.helpers.UndefinedExecutionExceptionError: Exception mismatch on Transaction ({'index': 0, 'nonce': 0}):
FAILED tests/osaka/eip7825_transaction_gas_limit_cap/test_tx_gas_limit.py::test_transaction_gas_limit_cap[fork_Osaka-tx_gas_limit_cap_exceeds_maximum3-blockchain_test_engine_from_state_test] - ethereum_test_specs.helpers.UndefinedExecutionExceptionError: Exception mismatch on Transaction ({'index': 0, 'nonce': 0}):
FAILED tests/osaka/eip7825_transaction_gas_limit_cap/test_tx_gas_limit.py::test_transaction_gas_limit_cap[fork_Osaka-tx_gas_limit_cap_exceeds_maximum4-state_test] - ethereum_test_specs.helpers.UndefinedExecutionExceptionError: Exception mismatch on Transaction ({'index': 0, 'nonce': 0}):
FAILED tests/osaka/eip7825_transaction_gas_limit_cap/test_tx_gas_limit.py::test_transaction_gas_limit_cap[fork_Osaka-tx_gas_limit_cap_exceeds_maximum4-blockchain_test_from_state_test] - ethereum_test_specs.helpers.UndefinedExecutionExceptionError: Exception mismatch on Transaction ({'index': 0, 'nonce': 0}):
FAILED tests/osaka/eip7825_transaction_gas_limit_cap/test_tx_gas_limit.py::test_transaction_gas_limit_cap[fork_Osaka-tx_gas_limit_cap_exceeds_maximum4-blockchain_test_engine_from_state_test] - ethereum_test_specs.helpers.UndefinedExecutionExceptionError: Exception mismatch on Transaction ({'index': 0, 'nonce': 0}):
FAILED tests/osaka/eip7825_transaction_gas_limit_cap/test_tx_gas_limit.py::test_tx_gas_limit_cap_full_calldata[fork_Osaka-state_test-zero_byte_True-exceed_tx_gas_limit_True-correct_intrinsic_cost_in_transaction_gas_limit_True] - ethereum_test_specs.helpers.UndefinedExecutionExceptionError: Exception mismatch on Transaction ({'index': 0, 'nonce': 0}):
FAILED tests/osaka/eip7825_transaction_gas_limit_cap/test_tx_gas_limit.py::test_tx_gas_limit_cap_full_calldata[fork_Osaka-state_test-zero_byte_False-exceed_tx_gas_limit_True-correct_intrinsic_cost_in_transaction_gas_limit_True] - ethereum_test_specs.helpers.UndefinedExecutionExceptionError: Exception mismatch on Transaction ({'index': 0, 'nonce': 0}):
FAILED tests/osaka/eip7825_transaction_gas_limit_cap/test_tx_gas_limit.py::test_tx_gas_limit_cap_full_calldata[fork_Osaka-blockchain_test_from_state_test-zero_byte_True-exceed_tx_gas_limit_True-correct_intrinsic_cost_in_transaction_gas_limit_True] - ethereum_test_specs.helpers.UndefinedExecutionExceptionError: Exception mismatch on Transaction ({'index': 0, 'nonce': 0}):
FAILED tests/osaka/eip7825_transaction_gas_limit_cap/test_tx_gas_limit.py::test_tx_gas_limit_cap_full_calldata[fork_Osaka-blockchain_test_from_state_test-zero_byte_False-exceed_tx_gas_limit_True-correct_intrinsic_cost_in_transaction_gas_limit_True] - ethereum_test_specs.helpers.UndefinedExecutionExceptionError: Exception mismatch on Transaction ({'index': 0, 'nonce': 0}):
FAILED tests/osaka/eip7825_transaction_gas_limit_cap/test_tx_gas_limit.py::test_tx_gas_limit_cap_full_calldata[fork_Osaka-blockchain_test_engine_from_state_test-zero_byte_True-exceed_tx_gas_limit_True-correct_intrinsic_cost_in_transaction_gas_limit_True] - ethereum_test_specs.helpers.UndefinedExecutionExceptionError: Exception mismatch on Transaction ({'index': 0, 'nonce': 0}):
FAILED tests/osaka/eip7825_transaction_gas_limit_cap/test_tx_gas_limit.py::test_tx_gas_limit_cap_full_calldata[fork_Osaka-blockchain_test_engine_from_state_test-zero_byte_False-exceed_tx_gas_limit_True-correct_intrinsic_cost_in_transaction_gas_limit_True] - ethereum_test_specs.helpers.UndefinedExecutionExceptionError: Exception mismatch on Transaction ({'index': 0, 'nonce': 0}):
FAILED tests/osaka/eip7825_transaction_gas_limit_cap/test_tx_gas_limit.py::test_tx_gas_limit_cap_access_list_with_diff_keys[fork_Osaka-state_test-exceed_tx_gas_limit_True-correct_intrinsic_cost_in_transaction_gas_limit_True] - ethereum_test_specs.helpers.UndefinedExecutionExceptionError: Exception mismatch on Transaction ({'index': 0, 'nonce': 0}):
FAILED tests/osaka/eip7825_transaction_gas_limit_cap/test_tx_gas_limit.py::test_tx_gas_limit_cap_access_list_with_diff_keys[fork_Osaka-blockchain_test_from_state_test-exceed_tx_gas_limit_True-correct_intrinsic_cost_in_transaction_gas_limit_True] - ethereum_test_specs.helpers.UndefinedExecutionExceptionError: Exception mismatch on Transaction ({'index': 0, 'nonce': 0}):
FAILED tests/osaka/eip7825_transaction_gas_limit_cap/test_tx_gas_limit.py::test_tx_gas_limit_cap_access_list_with_diff_keys[fork_Osaka-blockchain_test_engine_from_state_test-exceed_tx_gas_limit_True-correct_intrinsic_cost_in_transaction_gas_limit_True] - ethereum_test_specs.helpers.UndefinedExecutionExceptionError: Exception mismatch on Transaction ({'index': 0, 'nonce': 0}):
FAILED tests/osaka/eip7825_transaction_gas_limit_cap/test_tx_gas_limit.py::test_tx_gas_limit_cap_access_list_with_diff_addr[fork_Osaka-state_test-exceed_tx_gas_limit_True-correct_intrinsic_cost_in_transaction_gas_limit_True] - ethereum_test_specs.helpers.UndefinedExecutionExceptionError: Exception mismatch on Transaction ({'index': 0, 'nonce': 0}):
FAILED tests/osaka/eip7825_transaction_gas_limit_cap/test_tx_gas_limit.py::test_transaction_gas_limit_cap[fork_Osaka-tx_gas_limit_cap_exceeds_maximum0-state_test] - ethereum_test_specs.helpers.UndefinedExecutionExceptionError: Exception mismatch on Transaction ({'index': 0, 'nonce': 0}):
FAILED tests/osaka/eip7825_transaction_gas_limit_cap/test_tx_gas_limit.py::test_transaction_gas_limit_cap[fork_Osaka-tx_gas_limit_cap_exceeds_maximum0-blockchain_test_from_state_test] - ethereum_test_specs.helpers.UndefinedExecutionExceptionError: Exception mismatch on Transaction ({'index': 0, 'nonce': 0}):
FAILED tests/osaka/eip7825_transaction_gas_limit_cap/test_tx_gas_limit.py::test_transaction_gas_limit_cap[fork_Osaka-tx_gas_limit_cap_exceeds_maximum0-blockchain_test_engine_from_state_test] - ethereum_test_specs.helpers.UndefinedExecutionExceptionError: Exception mismatch on Transaction ({'index': 0, 'nonce': 0}):
FAILED tests/osaka/eip7825_transaction_gas_limit_cap/test_tx_gas_limit.py::test_transaction_gas_limit_cap[fork_Osaka-tx_gas_limit_cap_exceeds_maximum1-state_test] - ethereum_test_specs.helpers.UndefinedExecutionExceptionError: Exception mismatch on Transaction ({'index': 0, 'nonce': 0}):
FAILED tests/osaka/eip7825_transaction_gas_limit_cap/test_tx_gas_limit.py::test_transaction_gas_limit_cap[fork_Osaka-tx_gas_limit_cap_exceeds_maximum1-blockchain_test_from_state_test] - ethereum_test_specs.helpers.UndefinedExecutionExceptionError: Exception mismatch on Transaction ({'index': 0, 'nonce': 0}):
FAILED tests/osaka/eip7825_transaction_gas_limit_cap/test_tx_gas_limit.py::test_tx_gas_limit_cap_access_list_with_diff_addr[fork_Osaka-blockchain_test_from_state_test-exceed_tx_gas_limit_True-correct_intrinsic_cost_in_transaction_gas_limit_True] - ethereum_test_specs.helpers.UndefinedExecutionExceptionError: Exception mismatch on Transaction ({'index': 0, 'nonce': 0}):
FAILED tests/osaka/eip7825_transaction_gas_limit_cap/test_tx_gas_limit.py::test_tx_gas_limit_cap_access_list_with_diff_addr[fork_Osaka-blockchain_test_engine_from_state_test-exceed_tx_gas_limit_True-correct_intrinsic_cost_in_transaction_gas_limit_True] - ethereum_test_specs.helpers.UndefinedExecutionExceptionError: Exception mismatch on Transaction ({'index': 0, 'nonce': 0}):
FAILED tests/osaka/eip7825_transaction_gas_limit_cap/test_tx_gas_limit.py::test_tx_gas_limit_cap_authorized_tx[fork_Osaka-state_test-exceed_tx_gas_limit_True-correct_intrinsic_cost_in_transaction_gas_limit_True] - ethereum_test_specs.helpers.UndefinedExecutionExceptionError: Exception mismatch on Transaction ({'index': 0, 'nonce': 0}):
FAILED tests/osaka/eip7825_transaction_gas_limit_cap/test_tx_gas_limit.py::test_tx_gas_limit_cap_authorized_tx[fork_Osaka-blockchain_test_from_state_test-exceed_tx_gas_limit_True-correct_intrinsic_cost_in_transaction_gas_limit_True] - ethereum_test_specs.helpers.UndefinedExecutionExceptionError: Exception mismatch on Transaction ({'index': 0, 'nonce': 0}):
FAILED tests/osaka/eip7825_transaction_gas_limit_cap/test_tx_gas_limit.py::test_tx_gas_limit_cap_authorized_tx[fork_Osaka-blockchain_test_engine_from_state_test-exceed_tx_gas_limit_True-correct_intrinsic_cost_in_transaction_gas_limit_True] - ethereum_test_specs.helpers.UndefinedExecutionExceptionError: Exception mismatch on Transaction ({'index': 0, 'nonce': 0}):
FAILED tests/osaka/eip7825_transaction_gas_limit_cap/test_tx_gas_limit_transition_fork.py::test_transaction_gas_limit_cap_at_transition[fork_PragueToOsakaAtTime15k-blockchain_test-above_cap] - ethereum_test_specs.helpers.UndefinedExecutionExceptionError: Exception mismatch on Transaction ({'index': 0, 'nonce': 0}):
FAILED tests/osaka/eip7825_transaction_gas_limit_cap/test_tx_gas_limit_transition_fork.py::test_transaction_gas_limit_cap_at_transition[fork_PragueToOsakaAtTime15k-blockchain_test_engine-above_cap] - ethereum_test_specs.helpers.UndefinedExecutionExceptionError: Exception mismatch on Transaction ({'index': 0, 'nonce': 0}):
FAILED tests/prague/eip6110_deposits/test_modified_contract.py::test_invalid_layout[fork_Osaka-blockchain_test-log_argument_pubkey_size-value_zero] - ethereum_test_specs.helpers.UnexpectedExecutionSuccessError: 
FAILED tests/prague/eip6110_deposits/test_modified_contract.py::test_invalid_layout[fork_Osaka-blockchain_test-log_argument_pubkey_size-value_max_uint256] - ethereum_test_specs.helpers.UnexpectedExecutionSuccessError: 
FAILED tests/prague/eip6110_deposits/test_modified_contract.py::test_invalid_layout[fork_Osaka-blockchain_test-log_argument_pubkey_offset-value_zero] - ethereum_test_specs.helpers.UnexpectedExecutionSuccessError: 
FAILED tests/prague/eip6110_deposits/test_modified_contract.py::test_invalid_layout[fork_Osaka-blockchain_test-log_argument_pubkey_offset-value_max_uint256] - ethereum_test_specs.helpers.UnexpectedExecutionSuccessError: 
FAILED tests/prague/eip6110_deposits/test_modified_contract.py::test_invalid_layout[fork_Osaka-blockchain_test-log_argument_withdrawal_credentials_size-value_zero] - ethereum_test_specs.helpers.UnexpectedExecutionSuccessError: 
FAILED tests/prague/eip6110_deposits/test_modified_contract.py::test_invalid_layout[fork_Osaka-blockchain_test-log_argument_withdrawal_credentials_size-value_max_uint256] - ethereum_test_specs.helpers.UnexpectedExecutionSuccessError: 
FAILED tests/prague/eip6110_deposits/test_modified_contract.py::test_invalid_layout[fork_Osaka-blockchain_test-log_argument_withdrawal_credentials_offset-value_zero] - ethereum_test_specs.helpers.UnexpectedExecutionSuccessError: 
FAILED tests/prague/eip6110_deposits/test_modified_contract.py::test_invalid_layout[fork_Osaka-blockchain_test-log_argument_withdrawal_credentials_offset-value_max_uint256] - ethereum_test_specs.helpers.UnexpectedExecutionSuccessError: 
FAILED tests/prague/eip6110_deposits/test_modified_contract.py::test_invalid_layout[fork_Osaka-blockchain_test-log_argument_amount_size-value_zero] - ethereum_test_specs.helpers.UnexpectedExecutionSuccessError: 
FAILED tests/prague/eip6110_deposits/test_modified_contract.py::test_invalid_layout[fork_Osaka-blockchain_test-log_argument_amount_size-value_max_uint256] - ethereum_test_specs.helpers.UnexpectedExecutionSuccessError: 
FAILED tests/prague/eip6110_deposits/test_modified_contract.py::test_invalid_layout[fork_Osaka-blockchain_test-log_argument_amount_offset-value_zero] - ethereum_test_specs.helpers.UnexpectedExecutionSuccessError: 
FAILED tests/prague/eip6110_deposits/test_modified_contract.py::test_invalid_layout[fork_Osaka-blockchain_test-log_argument_amount_offset-value_max_uint256] - ethereum_test_specs.helpers.UnexpectedExecutionSuccessError: 
FAILED tests/prague/eip6110_deposits/test_modified_contract.py::test_invalid_layout[fork_Osaka-blockchain_test-log_argument_signature_size-value_zero] - ethereum_test_specs.helpers.UnexpectedExecutionSuccessError: 
FAILED tests/prague/eip6110_deposits/test_modified_contract.py::test_invalid_layout[fork_Osaka-blockchain_test-log_argument_signature_size-value_max_uint256] - ethereum_test_specs.helpers.UnexpectedExecutionSuccessError: 
FAILED tests/prague/eip6110_deposits/test_modified_contract.py::test_invalid_layout[fork_Osaka-blockchain_test-log_argument_signature_offset-value_zero] - ethereum_test_specs.helpers.UnexpectedExecutionSuccessError: 
FAILED tests/prague/eip6110_deposits/test_modified_contract.py::test_invalid_layout[fork_Osaka-blockchain_test-log_argument_signature_offset-value_max_uint256] - ethereum_test_specs.helpers.UnexpectedExecutionSuccessError: 
FAILED tests/prague/eip6110_deposits/test_modified_contract.py::test_invalid_layout[fork_Osaka-blockchain_test-log_argument_index_size-value_zero] - ethereum_test_specs.helpers.UnexpectedExecutionSuccessError: 
FAILED tests/prague/eip6110_deposits/test_modified_contract.py::test_invalid_layout[fork_Osaka-blockchain_test-log_argument_index_size-value_max_uint256] - ethereum_test_specs.helpers.UnexpectedExecutionSuccessError: 
FAILED tests/prague/eip6110_deposits/test_modified_contract.py::test_invalid_layout[fork_Osaka-blockchain_test-log_argument_index_offset-value_zero] - ethereum_test_specs.helpers.UnexpectedExecutionSuccessError: 
FAILED tests/prague/eip6110_deposits/test_modified_contract.py::test_invalid_layout[fork_Osaka-blockchain_test-log_argument_index_offset-value_max_uint256] - ethereum_test_specs.helpers.UnexpectedExecutionSuccessError: 
FAILED tests/prague/eip6110_deposits/test_modified_contract.py::test_invalid_layout[fork_Osaka-blockchain_test_engine-log_argument_pubkey_size-value_zero] - ethereum_test_specs.helpers.UnexpectedExecutionSuccessError: 
FAILED tests/prague/eip6110_deposits/test_modified_contract.py::test_invalid_layout[fork_Osaka-blockchain_test_engine-log_argument_pubkey_size-value_max_uint256] - ethereum_test_specs.helpers.UnexpectedExecutionSuccessError: 
FAILED tests/prague/eip6110_deposits/test_modified_contract.py::test_invalid_layout[fork_Osaka-blockchain_test_engine-log_argument_pubkey_offset-value_zero] - ethereum_test_specs.helpers.UnexpectedExecutionSuccessError: 
FAILED tests/prague/eip6110_deposits/test_modified_contract.py::test_invalid_layout[fork_Osaka-blockchain_test_engine-log_argument_pubkey_offset-value_max_uint256] - ethereum_test_specs.helpers.UnexpectedExecutionSuccessError: 
FAILED tests/prague/eip6110_deposits/test_modified_contract.py::test_invalid_layout[fork_Osaka-blockchain_test_engine-log_argument_withdrawal_credentials_size-value_zero] - ethereum_test_specs.helpers.UnexpectedExecutionSuccessError: 
FAILED tests/prague/eip6110_deposits/test_modified_contract.py::test_invalid_layout[fork_Osaka-blockchain_test_engine-log_argument_withdrawal_credentials_size-value_max_uint256] - ethereum_test_specs.helpers.UnexpectedExecutionSuccessError: 
FAILED tests/prague/eip6110_deposits/test_modified_contract.py::test_invalid_layout[fork_Osaka-blockchain_test_engine-log_argument_withdrawal_credentials_offset-value_zero] - ethereum_test_specs.helpers.UnexpectedExecutionSuccessError: 
FAILED tests/prague/eip6110_deposits/test_modified_contract.py::test_invalid_layout[fork_Osaka-blockchain_test_engine-log_argument_withdrawal_credentials_offset-value_max_uint256] - ethereum_test_specs.helpers.UnexpectedExecutionSuccessError: 
FAILED tests/prague/eip6110_deposits/test_modified_contract.py::test_invalid_layout[fork_Osaka-blockchain_test_engine-log_argument_amount_size-value_zero] - ethereum_test_specs.helpers.UnexpectedExecutionSuccessError: 
FAILED tests/prague/eip6110_deposits/test_modified_contract.py::test_invalid_layout[fork_Osaka-blockchain_test_engine-log_argument_amount_size-value_max_uint256] - ethereum_test_specs.helpers.UnexpectedExecutionSuccessError: 
FAILED tests/prague/eip6110_deposits/test_modified_contract.py::test_invalid_layout[fork_Osaka-blockchain_test_engine-log_argument_amount_offset-value_zero] - ethereum_test_specs.helpers.UnexpectedExecutionSuccessError: 
FAILED tests/prague/eip6110_deposits/test_modified_contract.py::test_invalid_layout[fork_Osaka-blockchain_test_engine-log_argument_amount_offset-value_max_uint256] - ethereum_test_specs.helpers.UnexpectedExecutionSuccessError: 
FAILED tests/prague/eip6110_deposits/test_modified_contract.py::test_invalid_layout[fork_Osaka-blockchain_test_engine-log_argument_signature_size-value_zero] - ethereum_test_specs.helpers.UnexpectedExecutionSuccessError: 
FAILED tests/prague/eip6110_deposits/test_modified_contract.py::test_invalid_layout[fork_Osaka-blockchain_test_engine-log_argument_signature_size-value_max_uint256] - ethereum_test_specs.helpers.UnexpectedExecutionSuccessError: 
FAILED tests/prague/eip6110_deposits/test_modified_contract.py::test_invalid_layout[fork_Osaka-blockchain_test_engine-log_argument_signature_offset-value_zero] - ethereum_test_specs.helpers.UnexpectedExecutionSuccessError: 
FAILED tests/prague/eip6110_deposits/test_modified_contract.py::test_invalid_layout[fork_Osaka-blockchain_test_engine-log_argument_signature_offset-value_max_uint256] - ethereum_test_specs.helpers.UnexpectedExecutionSuccessError: 
FAILED tests/prague/eip6110_deposits/test_modified_contract.py::test_invalid_layout[fork_Osaka-blockchain_test_engine-log_argument_index_size-value_zero] - ethereum_test_specs.helpers.UnexpectedExecutionSuccessError: 
FAILED tests/prague/eip6110_deposits/test_modified_contract.py::test_invalid_layout[fork_Osaka-blockchain_test_engine-log_argument_index_size-value_max_uint256] - ethereum_test_specs.helpers.UnexpectedExecutionSuccessError: 
FAILED tests/prague/eip6110_deposits/test_modified_contract.py::test_invalid_layout[fork_Osaka-blockchain_test_engine-log_argument_index_offset-value_zero] - ethereum_test_specs.helpers.UnexpectedExecutionSuccessError: 
FAILED tests/prague/eip6110_deposits/test_modified_contract.py::test_invalid_layout[fork_Osaka-blockchain_test_engine-log_argument_index_offset-value_max_uint256] - ethereum_test_specs.helpers.UnexpectedExecutionSuccessError: 
FAILED tests/prague/eip6110_deposits/test_modified_contract.py::test_invalid_log_length[fork_Osaka-blockchain_test-slice_bytes_True] - ethereum_test_specs.helpers.UnexpectedExecutionSuccessError: 
FAILED tests/prague/eip6110_deposits/test_modified_contract.py::test_invalid_log_length[fork_Osaka-blockchain_test-slice_bytes_False] - ethereum_test_specs.helpers.UnexpectedExecutionSuccessError: 
FAILED tests/prague/eip6110_deposits/test_modified_contract.py::test_invalid_log_length[fork_Osaka-blockchain_test_engine-slice_bytes_True] - ethereum_test_specs.helpers.UnexpectedExecutionSuccessError: 
FAILED tests/prague/eip6110_deposits/test_modified_contract.py::test_invalid_log_length[fork_Osaka-blockchain_test_engine-slice_bytes_False] - ethereum_test_specs.helpers.UnexpectedExecutionSuccessError: 
FAILED tests/prague/eip7002_el_triggerable_withdrawals/test_modified_withdrawal_contract.py::test_system_contract_errors[fork_Osaka-blockchain_test-system_contract_out_of_gas-system_contract_0x00000961ef480eb55e80d19ad83579a64c007002] - ethereum_test_specs.helpers.UnexpectedExecutionSuccessError: 
FAILED tests/prague/eip7002_el_triggerable_withdrawals/test_modified_withdrawal_contract.py::test_system_contract_errors[fork_Osaka-blockchain_test-system_contract_reverts-system_contract_0x00000961ef480eb55e80d19ad83579a64c007002] - ethereum_test_specs.helpers.UnexpectedExecutionSuccessError: 
FAILED tests/prague/eip7002_el_triggerable_withdrawals/test_modified_withdrawal_contract.py::test_system_contract_errors[fork_Osaka-blockchain_test-system_contract_throws-system_contract_0x00000961ef480eb55e80d19ad83579a64c007002] - ethereum_test_specs.helpers.UnexpectedExecutionSuccessError: 
FAILED tests/prague/eip7002_el_triggerable_withdrawals/test_modified_withdrawal_contract.py::test_system_contract_errors[fork_Osaka-blockchain_test_engine-system_contract_out_of_gas-system_contract_0x00000961ef480eb55e80d19ad83579a64c007002] - ethereum_test_specs.helpers.UnexpectedExecutionSuccessError: 
FAILED tests/prague/eip7002_el_triggerable_withdrawals/test_modified_withdrawal_contract.py::test_system_contract_errors[fork_Osaka-blockchain_test_engine-system_contract_reverts-system_contract_0x00000961ef480eb55e80d19ad83579a64c007002] - ethereum_test_specs.helpers.UnexpectedExecutionSuccessError: 
FAILED tests/prague/eip7002_el_triggerable_withdrawals/test_modified_withdrawal_contract.py::test_system_contract_errors[fork_Osaka-blockchain_test_engine-system_contract_throws-system_contract_0x00000961ef480eb55e80d19ad83579a64c007002] - ethereum_test_specs.helpers.UnexpectedExecutionSuccessError: 
FAILED tests/prague/eip7251_consolidations/test_modified_consolidation_contract.py::test_system_contract_errors[fork_Osaka-blockchain_test-system_contract_out_of_gas-system_contract_0x0000bbddc7ce488642fb579f8b00f3a590007251] - ethereum_test_specs.helpers.UnexpectedExecutionSuccessError: 
FAILED tests/prague/eip7251_consolidations/test_modified_consolidation_contract.py::test_system_contract_errors[fork_Osaka-blockchain_test-system_contract_reverts-system_contract_0x0000bbddc7ce488642fb579f8b00f3a590007251] - ethereum_test_specs.helpers.UnexpectedExecutionSuccessError: 
FAILED tests/prague/eip7251_consolidations/test_modified_consolidation_contract.py::test_system_contract_errors[fork_Osaka-blockchain_test-system_contract_throws-system_contract_0x0000bbddc7ce488642fb579f8b00f3a590007251] - ethereum_test_specs.helpers.UnexpectedExecutionSuccessError: 
FAILED tests/prague/eip7251_consolidations/test_modified_consolidation_contract.py::test_system_contract_errors[fork_Osaka-blockchain_test_engine-system_contract_out_of_gas-system_contract_0x0000bbddc7ce488642fb579f8b00f3a590007251] - ethereum_test_specs.helpers.UnexpectedExecutionSuccessError: 
FAILED tests/prague/eip7251_consolidations/test_modified_consolidation_contract.py::test_system_contract_errors[fork_Osaka-blockchain_test_engine-system_contract_reverts-system_contract_0x0000bbddc7ce488642fb579f8b00f3a590007251] - ethereum_test_specs.helpers.UnexpectedExecutionSuccessError: 
FAILED tests/prague/eip7251_consolidations/test_modified_consolidation_contract.py::test_system_contract_errors[fork_Osaka-blockchain_test_engine-system_contract_throws-system_contract_0x0000bbddc7ce488642fb579f8b00f3a590007251] - ethereum_test_specs.helpers.UnexpectedExecutionSuccessError: 
```

### PR DESCRIPTION
**Pull request by pdobacz**
Closes #1337 . Requires a fix on EEST side in order to fill, I'll open a PR there after the Weld

### CODE REVIEW

File: test/state/requests.cpp [hunk 1]
```diff
@@ -63,33 +71,77 @@ std::optional<Requests> collect_deposit_requests(std::span<const TransactionRece
...
-            // Pubkey size is 8 bytes, but is padded to the word boundary, so takes 32 bytes.
-            // Skip over amount and signature size.
-            static constexpr auto SIGNATURE_OFFSET = AMOUNT_OFFSET + 32 + 32;
-            static constexpr auto SIGNATURE_SIZE = 96;
-            // Skip over signature and index size.
-            static constexpr auto INDEX_OFFSET = SIGNATURE_OFFSET + 96 + 32;
-            static constexpr auto INDEX_SIZE = 8;
+            // Read and validate the ABI offsets and lengths for the dynamic fields
+            // according to EIP-6110. If any check fails, collection is considered failed.
+            auto read_word_as_size = [&](size_t pos) -> std::optional<size_t> {
```
Comment (pdobacz) [inline test/state/requests.cpp]: is there a standard function to accomplish this? I would expect so, but couldn't find any

File: test/state/requests.cpp [hunk 2]
```diff
@@ -63,33 +71,78 @@ std::optional<Requests> collect_deposit_requests(std::span<const TransactionRece
...
             // Index is padded to the word boundary, so takes 32 bytes.
-            assert(log.data.size() == INDEX_OFFSET + 32);
+            assert(log.data.size() == INDEX_OFFSET + WORD + pad_to_words(INDEX_SIZE));
 
-            requests.append({&log.data[PUBKEY_OFFSET], PUBKEY_SIZE});
-            requests.append({&log.data[WITHDRAWAL_CREDS_OFFSET], WITHDRAWAL_CREDS_SIZE});
-            requests.append({&log.data[AMOUNT_OFFSET], AMOUNT_SIZE});
-            requests.append({&log.data[SIGNATURE_OFFSET], SIGNATURE_SIZE});
-            requests.append({&log.data[INDEX_OFFSET], INDEX_SIZE});
+            requests.append({&log.data[PUBKEY_OFFSET + WORD], PUBKEY_SIZE});
```
Comment (pdobacz) [inline test/state/requests.cpp:142]: note here, that since I needed to add validation and thus change the meaning of the variables, `_OFFSET` now points to the size word, not contents. It is in line with the EIP-6110 wording

**Review by chfast — COMMENTED** [review]
Why don't we fail EEST currently?

File: test/state/requests.cpp (hunk 1 above)
Comment (chfast) [reply test/state/requests.cpp]: Use `intx::be::unsafe::load<intx::uint256>` to load the value. Then check if not bigger than `std::limits<size_t>::max()`.

I'd actually use `uint32_t` for the size type here so this is architecture independent.

File: test/state/requests.cpp [hunk 3]
```diff
@@ -63,33 +71,78 @@ std::optional<Requests> collect_deposit_requests(std::span<const TransactionRece
...
+                for (size_t i = 0; i < leading; ++i)
+                    if (log.data[pos + i] != 0)
+                        return std::nullopt;  // too large to fit into size_t
+                size_t v = 0;
+                for (size_t i = leading; i < 32; ++i)
+                    v = (v << 8) | static_cast<unsigned char>(log.data[pos + i]);
+                return v;
+            };
+
+            constexpr size_t WORD = 32;
```
Comment (chfast) [inline test/state/requests.cpp]:
```suggestion
            static constexpr size_t WORD = 32;
```
to get proper compile-time constant.

File: test/state/requests.cpp [hunk 4]
```diff
@@ -63,33 +71,78 @@ std::optional<Requests> collect_deposit_requests(std::span<const TransactionRece
...
+            constexpr size_t AMOUNT_OFFSET =
+                WITHDRAWAL_OFFSET + WORD + pad_to_words(WITHDRAWAL_SIZE);
+            constexpr size_t AMOUNT_SIZE = 8;
+            constexpr size_t SIGNATURE_OFFSET = AMOUNT_OFFSET + WORD + pad_to_words(AMOUNT_SIZE);
+            constexpr size_t SIGNATURE_SIZE = 96;
+            constexpr size_t INDEX_OFFSET = SIGNATURE_OFFSET + WORD + pad_to_words(SIGNATURE_SIZE);
+            constexpr size_t INDEX_SIZE = 8;
+
+            // Offsets in the head point to the length-word of each dynamic field.
+            const std::array<size_t, 5> expected_offsets = {
```
Comment (chfast) [inline test/state/requests.cpp]:
```suggestion
            static constexpr std::array<size_t, 5> expected_offsets = {
```

File: test/state/requests.cpp [hunk 5]
```diff
@@ -63,33 +71,78 @@ std::optional<Requests> collect_deposit_requests(std::span<const TransactionRece
...
+
+            if (offsets != expected_offsets)
+                return std::nullopt;  // layout does not match expected EIP-6110 deposit layout
 
+            // Validate sizes of each field.
+            auto validate_size = [&](size_t offset, size_t expected_size) -> bool {
+                const auto size = read_word_as_size(offset);
+                return size.has_value() && (*size == expected_size);
+            };
+            if (!validate_size(PUBKEY_OFFSET, PUBKEY_SIZE) ||
```
Comment (chfast) [inline test/state/requests.cpp]: I'm confused here. Are we validating the compile-time constants here? If yes, convert this to a `static_assert`.

Comment (pdobacz) [reply test/state/requests.cpp]: nope, the first argument is for lookup in the `log.data`. I'll improve the name to be more natural

**Comment by pdobacz** [comment]
> > I've eyeballed the coverage report, all looks fine to me
> 
> This means we don't have the coverage for the case where the logs are empty.

we do, just not PRed yet, sorry to skip over this :) and thank you for cross-checking
https://github.com/ethereum/execution-spec-tests/compare/main...ipsilon:execution-spec-tests:tests/no-topics
